nexus:
  namespace: tools
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 3.6.0
  annotations:
    configmapReloader: nexus3-conf
    secretReloader: nexus-admin-account
  image:
    name: sonatype/nexus3
    tag: "3.6.0"
    pullPolicy: IfNotPresent
  services:
    docker:
      annotations:
        config.xposer.stakater.com/Domain: stackator.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Namespace}}.{{.Domain}}'
        config.xposer.stakater.com/TLS: "true"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          ingress.kubernetes.io/proxy-body-size: 900m
          certmanager.k8s.io/cluster-issuer: letsencrypt-production
    self:
      annotations:
        config.xposer.stakater.com/Domain: stackator.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Namespace}}.{{.Domain}}'
        config.xposer.stakater.com/TLS: "true"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          ingress.kubernetes.io/proxy-body-size: 900m
          certmanager.k8s.io/cluster-issuer: letsencrypt-production
# Add these annotations under self.annotations.xposer.stakater.com/annotations
# forecastle.stakater.com/expose: true
# forecastle.stakater.com/icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
  secrets:
    admin_account: ""
    cluster_account: ""
  probes:
    liveness:
      initialDelaySeconds: 1000
      timeoutSeconds: 10
    readiness:
      initialDelaySeconds: 30
      timeoutSeconds: 10
  persistence:
    enabled: true
    volumeClaimName: nexus-storage
  configFiles:
