nexus:
  namespace: tools
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 3.6.0
  image:
    name: sonatype/nexus3
    tag: "3.6.0"
    pullPolicy: IfNotPresent
  services:
    docker:
      ingressClass: internal-ingress
      forceSslRedirect: "true"
    self:
      ingressClass: internal-ingress
      forceSslRedirect: "true"
  secrets:
    admin_account: ""
    cluster_account: ""
  probes:
    liveness:
      initialDelaySeconds: 1000
      timeoutSeconds: 10
    readiness:
      initialDelaySeconds: 30
      timeoutSeconds: 10
  persistence:
    enabled: true
    volumeClaimName: nexus-storage
  configFiles:
