apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3-conf
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
data:
  {{- range $key, $value := .Values.nexus.configFiles }}
  {{ $key }}: |
{{ $value | indent 4}}
  {{- end }}
