apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" .}}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      initContainers:
      - name: fmp-volume-permission
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['chown', '-R', '200', '/nexus-data']
        volumeMounts:
          - name: nexus3-data
            mountPath: /nexus-data
      - name: fmp-volume-permission2
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['chmod', '-R', '777', '/nexus3-conf']
        volumeMounts:
          - name: nexus3-conf
            mountPath: /nexus3-conf
      containers:
        - name: {{ template "name" . }}
          image: "{{ .Values.nexus.image.name }}:{{ .Values.nexus.image.tag }}"
          imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "/nexus3-conf/postStart.sh"]
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: {{ .Values.nexus.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.nexus.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: {{ .Values.nexus.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.nexus.probes.readiness.timeoutSeconds }}
          ports:
            - containerPort: 8081
            - containerPort: 5000
          volumeMounts:
            - name: nexus3-data
              mountPath: /nexus-data
            - name: nexus3-conf
              mountPath: /nexus3-conf
            - name: admin-account-volume
              mountPath: /etc/secret-volume
              readOnly: true
      volumes:
      - name: nexus3-conf
        configMap:
          name: nexus3-conf
      - name: nexus3-data
        {{- if .Values.nexus.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.nexus.persistence.volumeClaimName }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: admin-account-volume
        secret:
          secretName: {{ template "name" . }}-admin-account
