apiVersion: v1
kind: Service
metadata:
{{- if .Values.nexus.services.docker.annotations }}
  annotations:
{{ toYaml .Values.nexus.services.docker.annotations | indent 4 }}
{{- end }}
  labels:
    expose: "true"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: docker
spec:
  ports:
  - name: docker
    port: 80
    targetPort: 5000
  selector:
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
