apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: {{ .Values.nexus.services.self.forceSslRedirect }}
      ingress.kubernetes.io/proxy-body-size: 900m
      kubernetes.io/ingress.class: {{ .Values.nexus.services.self.ingressClass }}
    {{- with .Values.nexus.forecastle.expose }}
      forecastle.stakater.com/expose: {{ . }}
    {{- end }}
    {{- with .Values.nexus.forecastle.icon }}
      forecastle.stakater.com/icon: {{ . }}
    {{- end }}
  labels:
    expose: "true"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
