apiVersion: v1
kind: Service
metadata:
{{- if .Values.nexus.services.self.annotations }}
  annotations:
{{ toYaml .Values.nexus.services.self.annotations | indent 4 }}
{{- end }}
  labels:
    expose: "true"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
