apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-conf
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
data:
  {{- range $key, $value := .Values.nexus3.configFiles }}
  {{ $key }}: {{ $value }}
  {{- end }}