apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" .}}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      initContainers:
      - name: fmp-volume-permission
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['chown', '-R', '200', '/{{ template "name" . }}-data']
        volumeMounts:
          - name: {{ template "name" . }}-data
            mountPath: /{{ template "name" . }}-data
      - name: fmp-volume-permission2
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['chmod', '-R', '777', '/{{ template "name" . }}-conf']
        volumeMounts:
          - name: {{ template "name" . }}-conf
            mountPath: /{{ template "name" . }}-conf
      containers:
        - name: {{ template "name" . }}
          image: "{{ .Values.nexus3.image.name }}:{{ .Values.nexus3.image.tag }}"
          imagePullPolicy: {{ .Values.nexus3.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "/{{ template "name" . }}-conf/postStart.sh"]
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: {{ .Values.nexus3.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.nexus3.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: {{ .Values.nexus3.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.nexus3.probes.readiness.timeoutSeconds }}
          ports:
            - containerPort: 8081
            - containerPort: 5000
          volumeMounts:
            - name: {{ template "name" . }}-data
              mountPath: /{{ template "name" . }}-data
            - name: {{ template "name" . }}-conf
              mountPath: /{{ template "name" . }}-conf
            - name: admin-account-volume
              mountPath: /etc/secret-volume
              readOnly: true
      volumes:
      - name: {{ template "name" . }}-conf
        configMap:
          name: {{ template "name" . }}-conf
      - name: {{ template "name" . }}-data
        {{- if .Values.nexus3.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.nexus3.persistence.volumeClaimName }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: admin-account-volume
        secret:
          secretName: {{ template "name" . }}-admin-account