apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: true
      ingress.kubernetes.io/proxy-body-size: 900m
      kubernetes.io/ingress.class: {{ .Values.nexus3.services.docker.ingressClass }}
  labels:
    expose: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: docker
spec:
  ports:
  - name: docker
    port: 80
    targetPort: 5000
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  type: ClusterIP

