apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}-pv
spec:
  capacity:
    storage: {{ .Values.nexusStorage.capacity }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.nexusStorage.efs.server }}
    path: "/nexus"
