apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nexusStorage.capacity }}
  volumeName: {{ template "name" . }}-pv
